before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/CoderSerio/pokemand-go/cmd.Version={{.Version}}
    main: .
    binary: pkmg

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE*
      
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: CoderSerio
    name: pokemand-go
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  footer: |
    ## Installation

    ### Using go install
    ```bash
    go install github.com/CoderSerio/pokemand-go@{{.Tag}}
    ```

    ### Or download binary
    Choose the appropriate binary for your system.

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser)